config/routes.rb
Rails.application.routes.draw do
  get 'partners/index'
  get 'products/index'

	get 'admin/api', to: 'page#api'
  if Rails.env.development? || Rails.env.test?
    mount Railsui::Engine, at: "/railsui"
  end

  # Inherits from Railsui::PageController#index
  # To overide, add your own page#index view or change to a new root
  # Visit the start page for Rails UI any time at /railsui/start
  # root action: :index, controller: "railsui/page"
   root 'home#index'

  # Rotas da API
  namespace :api do
    namespace :v1 do
      resources :products, only: [:index]
      resources :partners, only: [:index]
    end
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_person_name
  has_one_attached :avatar


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/partners_controller.rb
module Api
  module V1
    class PartnersController < ApplicationController
      def index
        @partners = Partner.all
        render json: @partners
      end
    end
  end
end

app/controllers/api/v1/products_controller.rb
module Api
  module V1
    class ProductsController < ApplicationController
      def index
        @products = Product.all
        render json: @products
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper Railsui::ThemeHelper

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :name])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController

	def api
		render layout: 'admin'
	end

	def home
		render layout: 'application'
	end

	def product
	end

	def partner
	end

end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  def index
    response = ShopApi.get_shop_info
    @partners = [response]
  end

  def show
    response = ShopApi.get_shop_info
    @partner = response
  end
end

app/controllers/products_controller.rb
# app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = ShopApi.get_products
  end
end

app/helpers/api/v1/partners_helper.rb
module Api::V1::PartnersHelper
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def number_to_currency(number, options = {})
    options[:precision] ||= 2
    options[:unit] ||= "R$"
    options[:separator] ||= "."
    options[:delimiter] ||= ","
    "#{options[:unit]}#{number_with_precision(number, options)}"
  end

  def number_with_precision(number, options = {})
    rounded_number = number.round(options[:precision])
    integer_part, fractional_part = rounded_number.to_s.split('.')
    fractional_part = (fractional_part || "").ljust(options[:precision], '0')
    "#{integer_part}#{options[:separator]}#{fractional_part}"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<div class="container mx-auto px-4 md:py-16 py-6">
  <div class="text-center">
    <h1 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">Welcome to Buscatex</h1>
    <p class="font-light text-base text-zinc-700 tracking-normal mt-3 dark:text-zinc-300">Explore our products and partners.</p>

    <div class="mt-8 flex justify-center">
      <%= link_to products_index_path, class: "btn-image mx-2 relative" do %>
        <div class="border border-zinc-300/90 shadow-sm shadow-zinc-300/20 rounded-lg p-3 dark:shadow-zinc-950/50 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:ring-zinc-600/30 dark:focus:border-zinc-600">
          <%= image_tag "home/shop_cart.jpeg", class: "rounded h-[174px] w-full object-cover object-center dark:border dark:border-zinc-600/80 border-transparent", alt: "Products Image" %>
        </div>
      <% end %>

      <%= link_to partners_index_path, class: "btn-image mx-2 relative" do %>
        <div class="border border-zinc-300/90 shadow-sm shadow-zinc-300/20 rounded-lg p-3 dark:shadow-zinc-950/50 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:ring-zinc-600/30 dark:focus:border-zinc-600">
          <%= image_tag "home/store.jpeg", class: "rounded h-[174px] w-full object-cover object-center dark:border dark:border-zinc-600/80 border-transparent", alt: "Partners Image" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Railsui.config.application_name || "Buscatex " %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "https://unpkg.com/trix@2.0.0/dist/trix.css", "https://unpkg.com/photoswipe@5.4.2/dist/photoswipe.css", "data-turbo-track": "reload" %>

    <%= render "shared/fonts" %>
    <%= render "shared/meta" %>
    <%= custom_colors_css %>
    <%= yield :head %>
  </head>

  <body class="h-full antialiased text-zinc-800 leading-normal selection:bg-primary-100 selection:text-primary-700 dark:bg-zinc-900 bg-white dark:text-zinc-50 dark:selection:bg-zinc-500/40 dark:selection:text-zinc-200" data-controller="dark-mode search">
    <%= render "shared/flash" %>
    <% if content_for(:header).present? %>
      <%= yield :header %>
    <% else %>
      <%= render "shared/nav" %>
    <% end %>
    <%= yield %>
    <%= railsui_launcher if Rails.env.development? %>
    <%= render "shared/search_overlay" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Buscatex" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "https://unpkg.com/trix@2.0.0/dist/trix.css", "data-turbo-track": "reload" %>

    <%= render "shared/fonts" %>
    <%= render "shared/meta" %>
    <%= custom_colors_css %>
    <%= yield :head %>
  </head>

  <body class="h-full antialiased text-zinc-800 leading-normal selection:bg-primary-100 selection:text-primary-700 dark:bg-zinc-900 bg-white dark:text-zinc-50 dark:selection:bg-zinc-500/40 dark:selection:text-zinc-200" data-controller="dark-mode search pricing">
    <%= render "shared/flash" %>
    <% if content_for(:header).present? %>
      <%= yield :header %>
    <% else %>
      <%= render "shared/nav" %>
    <% end %>
    <%= yield %>
    <%= railsui_launcher if Rails.env.development? %>
    <%= render "shared/search_overlay" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Railsui.config.application_name || "Buscatex " %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "https://unpkg.com/trix@2.0.0/dist/trix.css", "data-turbo-track": "reload" %>

    <%= render "shared/fonts" %>
    <%= render "shared/meta" %>
    <%= custom_colors_css %>
    <%= yield :head %>
  </head>

  <body class="h-full antialiased text-zinc-800 leading-normal selection:bg-primary-100 selection:text-primary-700 dark:bg-zinc-900 bg-white dark:text-zinc-50 dark:selection:bg-zinc-500/40 dark:selection:text-zinc-200" data-controller="dark-mode search">
    <%= render "shared/flash" %>
    <%= yield %>
    <%= railsui_launcher if Rails.env.development? %>
  </body>
</html>

app/views/partners/_partner.html.erb
<div class="border border-zinc-300/90 shadow-sm shadow-zinc-300/20 rounded-lg p-3 dark:shadow-zinc-950/50 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:ring-zinc-600/30 dark:focus:border-zinc-600 relative w-64 mx-auto flex flex-col items-center" style="width: 250px;">
  <div class="rounded h-[250px] w-[250px] bg-zinc-200 dark:bg-zinc-700 border dark:border-zinc-600/80 border-transparent mb-4 flex items-center justify-center">
    <span class="text-xl font-semibold text-zinc-900 dark:text-zinc-100"><%= partner['name'] %></span>
  </div>
  <h3 class="text-lg font-semibold text-zinc-900 dark:text-zinc-100 mb-2 text-center"><%= partner['name'] %></h3>
  <p class="text-sm text-zinc-700 dark:text-zinc-300 mb-2 text-center"><%= partner['owner'] %></p>
  <p class="text-sm text-zinc-700 dark:text-zinc-300 mb-2 text-center"><%= partner['color'] %></p>
</div>

app/views/partners/index.html.erb
<!-- app/views/partners/index.html.erb -->
<div class="container mx-auto px-4 md:py-16 py-6">
  <div class="text-center">
    <h1 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">Partners</h1>
    <p class="font-light text-base text-zinc-700 tracking-normal mt-3 dark:text-zinc-300">Explore our partners.</p>
  </div>

    <div class="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6">
      <% @partners.each do |partner| %>
        <%= render 'partner', partner: partner %>
      <% end %>
    </div>
  </div>
</div>

app/views/partners/show.html.erb
<%= render 'partner', partner: @partner %>

app/views/products/_product.html.erb
<!-- app/views/products/_product.html.erb -->
<div class="border border-zinc-300/90 shadow-sm shadow-zinc-300/20 rounded-lg p-3 dark:shadow-zinc-950/50 dark:bg-zinc-800/90 dark:border-zinc-600/80 dark:focus:ring-zinc-600/30 dark:focus:border-zinc-600 relative w-64 mx-auto flex flex-col items-center" style="width: 250px;">
  <%= image_tag product['photo'], class: "rounded h-[250px] w-[250px] object-cover object-center dark:border dark:border-zinc-600/80 border-transparent mb-4", alt: product['name'] %>
  <h3 class="text-lg font-semibold text-zinc-900 dark:text-zinc-100 mb-2 text-center"><%= product['name'] %></h3>
  <p class="text-sm text-zinc-700 dark:text-zinc-300 mb-4 text-center">
    <% if product['is_promotion'] %>
      <span class="line-through"><%= tag.p tag.s number_to_currency(product['price']) %></span>
      <span class="text-red-600"><%= number_to_currency(product['price'].to_f * 0.8) %></span>
    <% else %>
      <%= number_to_currency(product['price']) %>
    <% end %>
  </p>
  <% if product['is_promotion'] %>
    <span class="absolute top-2 left-2 bg-red-500 text-white px-2 py-1 text-xs font-semibold rounded">Promotion</span>
  <% end %>
  <p class="text-sm text-zinc-700 dark:text-zinc-300 mb-2 text-center"><strong>Category:</strong> <%= product['category']['type'] %></p>
  <% if product['category']['type'] == 'TI' %>
    <p class="text-sm text-zinc-700 dark:text-zinc-300 mb-2 text-center"><strong>S.O:</strong> <%= product['category']['subcategory'] %></p>
  <% elsif product['category']['type'] == 'Eletrodomestico' %>
    <p class="text-sm text-zinc-700 dark:text-zinc-300 mb-2 text-center"><strong>Volt:</strong> <%= product['category']['subcategory'] %></p>
  <% end %>
</div>

app/views/products/index.html.erb
<!-- app/views/products/index.html.erb -->
<div class="container mx-auto px-4 md:py-16 py-6">
  <div class="text-center">
    <h1 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">Products</h1>
    <p class="font-light text-base text-zinc-700 tracking-normal mt-3 dark:text-zinc-300">Explore our range of products.</p>
  </div>

  <div class="mt-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
    <% @products.each do |product| %>
      <%= render partial: "product", locals: { product: product } %>
    <% end %>
  </div>

</div>

app/views/shared/_email_action.html.erb
<%# locals: (align: "center", url: root_url, action:, theme: "primary", fullwidth: false) %>

<table class="action" align="<%= align %>">
  <tr>
    <td align="<%= align %>">
      <a href="<%= url %>" class="action__link action__link--<%= theme %> <%= fullwidth == true ? "action__link--expanded" : nil %>" target="_blank"><%= action %></a>
      <div itemscope itemtype="http://schema.org/EmailMessage">
        <div itemprop="potentialAction" itemscope itemtype="http://schema.org/ViewAction">
          <link itemprop="target" href="<%= url %>"/>
          <meta itemprop="name" content="<%= action %>"/>
        </div>
      </div>
    </td>
  </tr>
</table>

app/views/shared/_email_spacer.html.erb
<table class="spacer">
  <tbody>
    <tr>
      <td height="<%= amount %>" style="font-size:<%= amount %>px;line-height:<%= amount %>px;">&nbsp;</td>
    </tr>
  </tbody>
</table>
x

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="bg-primary-50/50 text-primary-700 sm:px-9 sm:py-6 px-6 py-6 rounded-lg mb-6 dark:bg-primary-400/10 dark:border dark:border-primary-400/20 dark:text-primary-50 text-sm" role="alert">
    <p class="font-semibold font-heading"><%= pluralize(resource.errors.count, "error") %> prohibited this post from being saved:</p>
    <ul class="list-disc mt-3 ml-4">
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="bg-secondary-600 text-white text-center p-4" role="alert">
    <p><%= sanitize notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="bg-primary-600 text-white text-center p-4" role="alert">
    <p><%= sanitize alert %></p>
  </div>
<% end %>

app/views/shared/_fonts.html.erb
 <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Lexend:wght@300;400;500;600;700;800&display=swap"
    rel="stylesheet">

app/views/shared/_footer.html.erb
<footer class="container mx-auto px-4 pb-10 font-heading">
  <div class="grid md:grid-cols-4 grid-cols-2 gap-6">
    <div>
      <h4 class="text-zinc-800 text-lg font-medium mb-4 dark:text-zinc-50">Support</h4>
      <ul class="leading-[2.8rem] text-zinc-500/90 dark:text-zinc-400/90">

        <li>
          <%= link_to "Get help", (defined?(admin_help_center_path) ? admin_help_center_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <a href="#" class="hover:text-zinc-700 dark:hover:text-zinc-300/90">Forum</a>
        </li>

        <li>
          <%= link_to "Documentation", (defined?(admin_help_center_path) ? admin_help_center_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <a href="#" class="hover:text-zinc-700 dark:hover:text-zinc-300/90">Tutorials</a>
        </li>

        <li>
          <%= link_to "Product updates", (defined?(admin_changelog_path) ? admin_changelog_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <%= link_to "Give feedback", (defined?(admin_contact_path) ? admin_contact_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>
      </ul>
    </div>
    <div>
      <h4 class="text-zinc-800 text-lg font-medium mb-4 dark:text-zinc-50">Hosting</h4>
      <ul class="leading-[2.8rem] text-zinc-500/90 dark:text-zinc-400/90">

        <li>
          <%= link_to "Pricing", (defined?(pricing_path) ? pricing_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <%= link_to "Resources", (defined?(admin_help_center_path) ? admin_help_center_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>
        <li>
          <%= link_to "Affiliates", "#", class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>
        <li>
          <%= link_to "Integrations", "#", class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <%= link_to "API Access", (defined?(admin_api_path) ? admin_api_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <a href="#" class="hover:text-zinc-700 dark:hover:text-zinc-300/90">Booking direct</a>
        </li>
      </ul>
    </div>
    <div>
      <h4 class="text-zinc-800 text-lg font-medium mb-4 dark:text-zinc-50">Company</h4>
      <ul class="leading-[2.8rem] text-zinc-500/90 dark:text-zinc-400/90">

        <li>
          <%= link_to "About us", (defined?(about_path) ? about_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>

        <li>
          <a href="#" class="hover:text-zinc-700 dark:hover:text-zinc-300/90">Careers</a>
        </li>
        <li>
          <a href="#" class="hover:text-zinc-700 dark:hover:text-zinc-300/90">Blog</a>
        </li>

        <li>
          <%= link_to "Contact us", (defined?(admin_contact_path) ? admin_contact_path : "#"), class: "hover:text-zinc-700 dark:hover:text-zinc-300/90" %>
        </li>
      </ul>
    </div>
    <div></div>
  </div>

  <div
    class="md:flex items-center pt-6 mt-16 border-t border-zinc-300/50 dark:border-zinc-600/50 flex-wrap md:justify-start justify-center">
    <div class="md:flex-1 md:flex items-center">
      <%= link_to root_path, class: "flex items-center md:space-x-3 justify-center md:justify-start group" do %>
        <svg class="fill-current text-zinc-900 dark:text-zinc-100 dark:group-hover:text-white" width="36" height="36"
          viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" clip-rule="evenodd"
            d="M30 0C33.3137 0 36 2.68629 36 6V30C36 33.3137 33.3137 36 30 36H6C2.68629 36 0 33.3137 0 30V6C0 2.68629 2.68629 0 6 0H30ZM16.1275 30.7111C16.3442 30.7438 16.5195 30.5309 16.5195 30.3117V25.6407C16.5195 23.3795 14.0716 21.9662 12.1133 23.0968C11.4052 23.5057 10.4997 23.2631 10.0909 22.5549C9.68208 21.8468 9.9247 20.9413 10.6328 20.5325C12.6123 19.3896 12.6123 16.5325 10.6328 15.3896C9.9247 14.9808 9.68208 14.0753 10.0909 13.3672C10.4997 12.6591 11.4052 12.4165 12.1133 12.8253C14.0716 13.9559 16.5195 12.5426 16.5195 10.2814V9.1364C16.5195 6.97891 14.5901 5.27606 12.6335 6.1852C8.20999 8.24062 5.14286 12.7232 5.14286 17.9221C5.14286 24.403 9.90907 29.7706 16.1275 30.7111ZM31.013 17.9221C31.013 24.4524 26.1737 29.8525 19.8856 30.7318C19.6601 30.7634 19.4805 30.5395 19.4805 30.3117V25.5541C19.4805 23.3069 21.9132 21.9024 23.8594 23.026C24.5675 23.4348 25.473 23.1922 25.8818 22.4841C26.2907 21.776 26.048 20.8705 25.3399 20.4617C23.415 19.3503 23.415 16.5718 25.3399 15.4605C26.048 15.0516 26.2907 14.1462 25.8818 13.438C25.473 12.7299 24.5675 12.4873 23.8594 12.8961C21.9132 14.0198 19.4805 12.6152 19.4805 10.368V9.11727C19.4805 6.95171 21.4035 5.2311 23.3785 6.11944C27.8792 8.14385 31.013 12.667 31.013 17.9221Z" />
        </svg>

        <span
          class="font-semibold text-xl lg:block hidden dark:text-zinc-100 dark:group-hover:text-white">Shepherd</span>
      <% end %>

      <ul
        class="md:flex md:w-auto w-full items-center md:space-x-4 font-light md:ml-4 text-zinc-500 md:text-left text-center md:leading-normal leading-loose my-5 md:my-0 md:text-base text-sm dark:text-zinc-500">
        <li>&copy; 2023, Shepherd Inc.</li>

        <li>
          <%= link_to "Terms", (defined?(admin_terms_path) ? admin_terms_path : "#"), class: "hover:text-zinc-800 dark:hover:text-zinc-400" %>
        </li>

        <li>
          <%= link_to "Privacy", (defined?(admin_privacy_path) ? admin_privacy_path : "#"), class: "hover:text-zinc-800 dark:hover:text-zinc-400" %>
        </li>
      </ul>
    </div>

    <ul class="flex justify-center items-center space-x-8">
      <li>
        <%= link_to "#", class: "group" do %>
          <%= icon "instagram.svg", path: "social/instagram.svg", classes: "w-6 h-6 fill-current text-zinc-700 dark:text-zinc-600 dark:group-hover:text-white group-hover:text-zinc-800" %>
        <% end %>
      </li>

      <li>
        <%= link_to "#", class: "group" do %>
          <%= icon "x.svg", path: "social/x.svg", classes: "w-6 h-6 fill-current text-zinc-700 dark:text-zinc-600 dark:group-hover:text-white group-hover:text-zinc-800" %>
        <% end %>
      </li>

      <li>
        <%= link_to "#", class: "group" do %>
          <%= icon "facebook", path: "social/facebook.svg", classes: "w-6 h-6 fill-current text-zinc-700 dark:text-zinc-600 dark:group-hover:text-white group-hover:text-zinc-800" %>
        <% end %>
      </li>

      <li>
        <%= link_to "#", class: "group" do %>
          <%= icon "linkedin", path: "social/linkedin.svg", classes: "w-6 h-6 fill-current text-zinc-700 dark:text-zinc-600 dark:group-hover:text-white group-hover:text-zinc-800" %>
        <% end %>
      </li>

      <li>
        <%= link_to "#", class: "group" do %>
          <%= icon "youtube", path: "social/youtube.svg", classes: "w-6 h-6 fill-current text-zinc-700 dark:text-zinc-600 dark:group-hover:text-white group-hover:text-zinc-800" %>
        <% end %>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_nav.html.erb
<header class="bg-white dark:bg-zinc-900 px-4 md:py-2 py-3 border-b border-zinc-300/80 relative z-50 dark:border-zinc-700/80" data-controller="nav">
  <%= render "shared/nav_menu" %>
</header>

app/views/shared/_nav_links.html.erb
<li>
  <%= nav_link_to "Products", products_index_path, class: "nav-link" %>
</li>
<li>
  <%= nav_link_to "Partners", partners_index_path, class: "nav-link" %>
</li>
<li>
  <%= nav_link_to "API", api_v1_products_path, class: "nav-link" %>
</li>

app/views/shared/_search_overlay.html.erb
<div data-search-target="overlay"
  class="hidden fixed w-screen h-screen bg-white/70 dark:bg-zinc-950/90 backdrop-blur-md z-[60] px-4 left-0 right-0 top-0 bottom-0"
  data-transition-enter-active="transition ease-out duration-100"
  data-transition-enter-from="transform opacity-0 scale-95" data-transition-enter-to="transform opacity-100 scale-100"
  data-transition-leave-active="transition ease-in duration-100"
  data-transition-leave-from="transform opacity-100 scale-100" data-transition-leave-to="transform opacity-0 scale-95">
  <div class="absolute top-4 md:right-10 right-4">
    <button class="btn btn-white px-3" data-action="click->search#close">
      <svg class="w-5 h-5 text-zinc-700 stroke-current pointer-events-none dark:text-zinc-100"
        xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <title>x-mark</title>
        <g fill="none">
          <path d="M6 18L18 6M6 6l12 12" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
          </path>
        </g>
      </svg>
    </button>
  </div>
  <div class="flex flex-col items-center h-full w-full justify-center">
    <div
      class="md:w-[600px] w-full max-w-2xl mx-auto bg-white dark:bg-zinc-800 rounded-lg md:rounded-3xl shadow-xl shadow-zinc-300/30 dark:shadow-zinc-950/30 md:p-16 p-6 border border-zinc-300/80 dark:border-zinc-700/80"
      data-search-target="content">
      <form action="#">
        <input type="text" data-search-target="input" placeholder="Search" class="form-input w-full">
      </form>
    </div>
  </div>
</div>

app/views/shared/admin/_nav_links.html.erb
<li>
  <%= nav_link_to "Api", send("admin_api_path"), class: "nav-link" %>
</li>